export const Constants = {
  WELCOME_TEXT: 'Business Details',
  ABOUT_BUSINESS_TEXT: 'Tell us about your Business',
  SELECT_OFFICER_TEXT: 'Select Officer',
  LOGIN_TEXT: 'As a part of banking compliance, you are required to identify yourself and your business',
  ENTER_COMPANY_TYPE: 'Select Your Company Type',
  ENTER_COMPANY_NAME: 'Enter Your Company Name / Number',
  SELECT_COMPANY: 'Select Your Company',
  ENTER_COMPANY_Activity: 'Enter Your Company Activity',
  ENTER_COMPANY_TURNOVER: 'Enter Your Expected Turnover Per Annum',
  ENTER_COMPANY_Website: 'Enter Company Website',
  ENTER_COMPANY_EMAIL: 'Enter Company Email',
  ENTER_COMPANY_PHONE: 'Enter Company Phone Number',
  ENTER_COMPANY_DeSCRIPTION: 'Enter About Company',
  ENTER_PRIVATE_ADDRESS: 'Enter Private Address',
  ENTER_SHIPPING_ADDRESS: 'Enter Shipping Address',
  ENTER_INVOICE_ADDRESS: 'Enter Invoice Address',
  ENTER_CORRESPONDENCE_ADDRESS: 'Enter Correspondence Address',
  OFFICER_FIRST_NAME: 'Officer First Name is Empty',
  OFFICER_LAST_NAME: 'Officer Last Name is Empty',
  OFFICER_DESIGNATION: 'Officer Designation is Empty',
  REMEMBER_ME_TEXT: 'Remember Me',
  FORGOT_PIN_TEXT: 'Forgot PIN?',
  BUTTON_TEXT: 'Proceed',
  DONT_HAVE_ACCOUNT_TEXT: 'Don’t have an account?',
  REGISTER_TEXT: 'Register',

  Email_Id_Required: 'Email Id is required',
  Pin_Required: 'Pin is required',
  COMPANYTYPE_REQUIRED: 'Select Company Type',
  COMPANYNAME_REQUIRED: 'Enter Company Name',
  COMPANYADDRESS_REQUIRED: 'Company Address not available',
  COMPANYNUMBER_REQUIRED: 'Company Number not available',
};
